# app/model.py
from pydantic import BaseModel, Field

class ChatRequest(BaseModel):
    message: str = Field(
        ..., 
        min_length=1, 
        max_length=2000, 
        description="The AML compliance investigator or analytics query string"
    )
    session_id: str = Field(
        default="default_session", 
        description="Unique thread tracking identifier isolating multi-turn chat context"
    )

class ChatResponse(BaseModel):
    session_id: str = Field(..., description="The matching session tracking identifier")
    response: str = Field(..., description="The clear textual answer generated by the agent model loop")
    status: str = Field(..., description="Execution state status metadata indicating 'success' or 'degraded_fallback'")